version: 2
updates:
- package-ecosystem: composer
  directories:
  - /
  - packages/**
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
- package-ecosystem: github-actions
  directories:
  - /
  - /packages/abstractions
  - /packages/authentication/phpleague
  - /packages/http/guzzle
  - /packages/serialization/form
  - /packages/serialization/json
  - /packages/serialization/multipart
  - /packages/serialization/text
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
